# Dictionary mapping variable names to their corresponding column indices in the dataset

aggregate_dict = {
    "eventID": 0,
    "vertexX": 1,
    "vertexY": 2,
    "vertexZ": 3,
    "reconstructedEnergy": 4,
    "directionX": 5,
    "directionY": 6,
    "directionZ": 7,
    "numberOfHits": 8,
    "numberOfPFParticles": 9,
    "trueOriginID": 10,
    "eventSequenceNumber": 11,
    "passSelectionCriterion": 12,
    "spillStatusFlag": 13,
    "eventTimestamp": 14,
    "totalNumberOfHits": 15,
    "triggerCandidateCount": 16,
    "groundShakeCount": 17,
    "sumOfLastADCTicks": 18,
    "sumOfTriggeredADCTicks": 19,
    "passSecondSelectionCriterion": 20,
    "energyDepositedInFirst10cm": 21,
    "energyDepositedInSecond10cm": 22,
    "energyDepositedInThird10cm": 23,
    "energyDepositedInFourth10cm": 24,
    "energyDepositedInFifth10cm": 25,
    "energyDepositedInSixth10cm": 26,
    "energyDepositedInSeventh10cm": 27,
    "energyDepositedInEighth10cm": 28,
    "energyDepositedInNinth10cm": 29,
    "energyDepositedInTenth10cm": 30,
    "energyDepositedInEleventh10cm": 31,
    "energyDepositedInTwelfth10cm": 32,
    "energyDepositedInThirteenth10cm": 33,
    "energyDepositedInFourteenth10cm": 34,
    "energyDepositedInFifteenth10cm": 35,
    "energyDepositedInFirst10cmBefore": 36,
    "energyDepositedInSecond10cmBefore": 37,
    "zROIStart": 38,
    "zROIEnd": 39,
    "timeROIStart": 40,
    "timeROIEnd": 41,
    "timeFitMean": 42,
    "timeFitSigma": 43,
    "directionX2": 44,
    "directionY2": 45,
    "directionZ2": 46,
    "lengthOfMuonTrack": 47,
    "numberOfHitsInSlice": 48
}
true_dict= {
    "eventID": 0,
    "vertexX": 1,
    "vertexY": 2,
    "vertexZ": 3,
    "energy": 4,
    "momentumX": 5,
    "momentumY": 6,
    "momentumZ": 7,
    "pdgCode": 8,
    "motherPdgCode": 9,
    "subrunTotalPOT": 10,
    "subrunGoodPOT": 11,
    "accumulatedPOT": 12,
    "triggerActivityFlag": 13,
    "eventSequenceNumber": 14
}
full_reco_dict = {
    "eventID": 0,
    "vertexX": 1,
    "vertexY": 2,
    "vertexZ": 3,
    "pdgCode": 4,
    "reconstructedEnergy": 5,
    "directionX": 6,
    "directionY": 7,
    "directionZ": 8,
    "numberOfHits": 9,
    "numberOfPFParticles": 10,
    "trueOriginID": 11,
    "eventSequenceNumber": 12,
    "passSelectionCriterion": 13
}



